repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        args: ["--fix"]
        name: lint
      - id: ruff-format
        name: format
        args: ["--diff"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: leak
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args: ["-r", "-s", "B101,B108", "--", "knowledge_flow_app", "knowledge_flow_app/tests"]
        name: sast
