# -----------------------------------------------------------------------------
# Backend development image
# -----------------------------------------------------------------------------
FROM mirror.gcr.io/python:3.12.8-slim

ARG USER_NAME=python-user
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG UV_VERSION=0.7.12

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl

# Copy project files
COPY .. /app

# Setup user
RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
    useradd -u ${USER_ID} -g ${GROUP_ID} -m ${USER_NAME} && \
    mkdir /opt/python && \
    chown -R ${USER_ID}:${GROUP_ID} /app /opt/python

# Change user
USER ${USER_NAME}

# Install uv
RUN curl -Ls https://astral.sh/uv/${UV_VERSION}/install.sh | bash

# Set the python virtual env into docker image
ENV VIRTUAL_ENV=/opt/python/venv
ENV PATH=/home/${USER_NAME}/.local/bin:${VIRTUAL_ENV}/bin:$PATH
ENV PYTHONPATH=/app
ENV ENV_CONFIG=/app/config/.env

# Move to workdir
WORKDIR /app

# Create python virtual env and install deps
RUN uv venv ${VIRTUAL_ENV} && \
    uv pip install -r uv.lock

# Expose Fast API port
EXPOSE 8111

# Define default entrypoint and command
ENTRYPOINT ["python"]
CMD ["/app/knowledge_flow_app/main.py"]