name: Setup environment
description: Create a virtual environment and install dependencies with uv 
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.12"
        enable-cache: true

    - name: Install the project
      run: |
        uv sync --extra dev
        echo "$HOME/.cache/uv/bin" >> $GITHUB_PATH
      shell: bash