_meta:
  type: "roles"
  config_version: 2

app_ro_role:
  index_permissions:
    - index_patterns:
        - "app-index"
      allowed_actions:
        - "read"

app_rw_role:
  index_permissions:
    - index_patterns:
        - "app-index"
      allowed_actions:
        - "read"
        - "write"
