name: Build and Push Docker Nightly Image

on:
  # schedule:
  #   - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Run linter, formatter, secrets detection and sast 
        run: pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Run tests with coverage
        run: tox -e test

  # build-and-push-image:
  #   runs-on: ubuntu-latest
  #   needs: [code-quality, unit-tests]

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Set lowercase repository name
  #       run: echo "LOWER_CASE_REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
  
  #     - name: Build and push nightly image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: dockerfiles/Dockerfile-prod
  #         push: true
  #         tags: ghcr.io/${{ env.LOWER_CASE_REPO }}:nightly
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
